version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped
    volumes:
      # - ./sql_dump:/docker-entrypoint-initdb.d
      - ./data_mysql:/var/lib/mysql
  web:
    build: .
    image: web
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html/
    ports:
      - "9000:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 9002:80
